### ISSUE TITLE
Drop in Taiwan, Province Of China: Cumulative Number Of Performed CV Tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#120]
Dear FIND,

Could you please check your time series "Taiwan, Province Of China: Cumulative Number Of Performed CV Tests" here:
https://raw.githubusercontent.com/dsbbfinddx/FINDCov19TrackerData/master/processed/coronavirus_tests.csv

We got 3 updates during the day and in latest revision 10/21/2021 period was revised to value in the initial release.

Could you please advise if second revision was some error?

Thank you.

**Comment by angelicambg** [comment]
Dear @DataOps-epam usually the automated process run twice a day, on that particular day was three times, but we only kept the last run at the end of the day because it is when most of the countries have updated their values. Unfortunately for that particular day, the last run didn't work, but for the next few days it has been running smoothly.
