### ISSUE TITLE
Bulgaria: Cumulative number of performed CV tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#177]
Hi team,
We can observe the largest jump in the history for the 3/15/2022 period and it looks suspicious to us.
Could you please check the data for the following series and advise what is the reason for the following jump?

**Comment by dsbb-finddx** [comment]
Hello @DataOps-epam thank you for your feedback. Bulgaria test data were not recently updated, hence the jump in the reported number.
The total number of performed tests we logged today seems to also agree with the [source](https://coronavirus.bg/).
Due to reporting infrequency, we have implemented linear interpolation on the time series, so it could be better if you could use the columns `all_new_tests` and `all_cum_tests` as well in your workflow.
I hope this helps :)

**Comment by DataOps-epam** [comment]
Thank you, this info is very helpful.
