### ISSUE TITLE
corrected columns in FINDCov19TrackerData/automated/countries-tests-all-dates.csv

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/FINDCov19TrackerData#25]
Are the _corrected columns going to be empty is this file? Shouldn't they be populated by default with the cumulative and new values and then corrected only when necessary?

**Comment by pat-s** [comment]
We can populate them with the cumulative and new values by default.

@dsbb-finddx Would it be possible to not assign all people by default? Tagging individuals is preferred since the "assigned" feature has a special meaning in GitHub.
A more passive way would be to adjust the personal "watch" or "notification" setting if one does not want to miss certain conversations.

**Comment by dsbb-finddx** [comment]
@pat-s Please populate them as you mentioned above.
Ok, noted re the assignment.

**Comment by pat-s** [comment]
Done so in https://github.com/dsbbfinddx/FINDCov19Tracker/commit/47ac0b98eeec2fe6c01fc3c288bb8c40d5b0f9e9.
