### ISSUE TITLE
Is countries-tests-all-dates.csv the file which will be used by shiny-data.R?

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/FINDCov19TrackerData#26]
The previous workflow was generating the coronavirus_tests.csv file which was then used in the [`shiy-data.R`](https://github.com/dsbbfinddx/FINDCov19Tracker/blob/master/R/shiny-data.R).
Is countries-tests-all-dates.csv going to be used in the [`shiy-data.R`](https://github.com/dsbbfinddx/FINDCov19Tracker/blob/master/R/shiny-data.R) script?

**Comment by pat-s** [comment]
Yes, this is the idea.

Beforehand the old data (i.e. `coronavirus_tests.csv`) should be merged into this file.

**Comment by ImaneElIdrissi** [comment]
I see that in _countries-tests-all-dates.csv_ there are countries like Afghanistan with "NA" for cumulative and/or new tests. @pat-s 
 I was wondering how are these "NA" going to be translated in the tracker? We don't want to show "NA" values and we will not always necessarily make manual checks right after the script is run. Thanks!

**Comment by pat-s** [comment]
@ImaneElIdrissi IIRC this was already discussed in the past with @christophsax and @dsbb-finddx to ensure that no NAs occur in the Shiny app. Please ask @christophsax for questions related to the Shiny app, thanks.

**Comment by christophsax** [comment]
The app displays `data_all.csv`, which has `NA`s for the last 3 days in AFG, and the app shows them that way.

I don't think this is an app problem.

``` r
library(tidyverse)

read_csv("https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/processed/data_all.csv?raw=true", col_types = cols()) %>% 
  filter(name == "Afghanistan") %>% 
  select(time, all_cum_tests, all_new_tests) %>% 
  tail(20)
#> # A tibble: 20 x 3
#>    time       all_cum_tests all_new_tests
#>    <date>             <dbl>         <dbl>
#>  1 2021-01-08        230250          2151
#>  2 2021-01-09        232401          2151
#>  3 2021-01-10        234551          2151
#>  4 2021-01-11        236702          2151
#>  5 2021-01-12        238853          2151
#>  6 2021-01-13        241004          2151
#>  7 2021-01-14        243155          2151
#>  8 2021-01-15        245305          2151
#>  9 2021-01-16        247456          2151
#> 10 2021-01-17        249607          2151
#> 11 2021-01-18        251758          2151
#> 12 2021-01-19        253908          2151
#> 13 2021-01-20        256059          2151
#> 14 2021-01-21        258210          2151
#> 15 2021-01-22        258210          2151
#> 16 2021-01-23        258210          2151
#> 17 2021-01-24        258210          2151
#> 18 2021-01-25        258210            NA
#> 19 2021-01-26        258210            NA
#> 20 2021-01-27        258210            NA
```

<sup>Created on 2021-01-29 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by pat-s** [comment]
I think we're talking about two different things here a bit:

- Anna and Imane refer to the output file to the new workflow `countries-tests-all-dates.csv`
- Christoph refers to `data_all.csv` which is for the old workflow

Nothing has changed how `data_all.csv` is processed since 2021-01-28 - I'll take a look what's happening.

**Comment by pat-s** [comment]
It looks like that the fix for #27 also fixed the Afghanistan case here.
I do not see why this started happening on 2021-01-28 though - there was no change to the code and no update of the {readr} package.

I'll open a new issue related to general NA handling.

**Comment by dsbb-finddx** [comment]
@pat-s @ImaneElIdrissi what Imane meant in the comment is that in the `countries-tests-all-dates.csv` if a country fails to have their data updated, instead of having the most recent values populating the current date, there are NAs in both new and cumulative tests columns. That should be fixed if she updates that country manually. But if she does not update it for one date, the NAs will ruin the time series for the country, since this is the final file for tests before creating the `data_all.csv`.

**Comment by pat-s** [comment]
> instead of having the most recent values populating the current date, there are NAs in both new and cumulative tests columns.

Yes. Based on these entries the files in https://github.com/dsbbfinddx/FINDCov19TrackerData/tree/master/issues are written.

> That should be fixed if she updates that country manually.

Correct.

> But if she does not update it for one date, the NAs will ruin the time series for the country, since this is the final file for tests before creating the data_all.csv

IMO this should be handled later down the line, i.e. within the shiny App. See also #29.

If we fake-insert values into country-date fields for which we actually have none, we create fake data.
Also I see high potential for internal confusion since it becomes hard to see which data we are actually missing and which we fake created.

Speaking from a statistian perspective, NA handling in time series is usually decoupled from the data gathering process.
Usually one wants to have the raw data (as raw as possible) and deal with NA handling afterwards.
And the creation of https://github.com/dsbbfinddx/FINDCov19TrackerData/blob/master/automated/countries-tests-all-dates.csv is the raw data in my view and therefore should include `NA` values if needed.

NAs can then easily be masked in time series handling to not affect longterm calculations or plots.
And I believe this should be done in https://github.com/dsbbfinddx/FINDCov19TrackerShiny.
