### ISSUE TITLE
Calculate automatically new tests and cumulative tests in manually updated files

### ISSUE THREAD

**Issue by angelicambg** [dsbbfinddx/FINDCov19TrackerData#32]
once the manual file is uploaded:

1. If there is a value in `tests_cumulative` and `new_tests` is empty, then calculate `new_tests`. This important to have it to start with the new workflow.
2. If there is a value in `new_tests` and `tests_cumulative` is empty then calculate  `tests_cumulative`. This can be an improvement after we start working with the new workflow.

**Comment by pat-s** [comment]
The title might be a bit misleading.

We already calculate `new_tests` automatically.
IIRC my intention was to merge all daily files of the last week into the file with the automated values - with the daily files overwriting the automated values because we assume that the manually gathered values are more correct.
