### ISSUE TITLE
Argentina wrong value on tests_cumulative_corrected column

### ISSUE THREAD

**Issue by dsbb-finddx** [dsbbfinddx/FINDCov19TrackerData#45]
@angelicambg Argentina for 2021-03-11 has a wrong value of 28882949 at the tests_cumulative_corrected column.
However the tracker shows the value of 7617966.

Why isn't the corrected column value as the original, since it was fetched automatically?
And why doesn't the tracker use the _corrected column value?

**Comment by angelicambg** [comment]
Argentina has not a fetched value for today. Therefore, to populate the values for `tests_cumulative_corrected` until today, the function `process_test_data()` was using the maximum value of (`tests_cumulative`) to generate `coronavirus_test.csv`.

Particularly for Argentina on 2020-10-27 there is a wrong value in `tests_cumulative`, which was corrected on `tests_cumulative_corrected`, but  `process_test_data()` took this value from `tests_cumulative`. Now, I changed the function in the package to take the maximum of `tests_cumulative_corrected` instead of `tests_cumulative`, when there is no new information coming from selenium, fetch, or manual files. Additionally, `new_tests` is calculated before filling these last dates without information, therefore `new_tests_corrected` was 0.

And this value was not shown in the app, because the value for `new_tests_corrected` was `0` and `create_shiny_data()` calculate `cum_tests` summing up the values for `new_tests_corrected`, which was correct.
