### ISSUE TITLE
Drop in cumulative values

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#46]
Hi, could you please check "tests_cumulative" for Venezuela. Previously today we got an update with "2971716" value for 03/11/2021 period and later got a revision for that period with drop to "2745122". Could you please confrim current data is correct and previous was wrong or clarify this. Thank you.

**Comment by dsbb-finddx** [comment]
@angelicambg @ImaneElIdrissi is this due to https://github.com/dsbbfinddx/FINDCov19TrackerData/issues/45#issuecomment-796800892

**Comment by ImaneElIdrissi** [comment]
Hi, we are scraping automatically Venezuela data from this website: https://covid19.patria.org.ve/noticia/dia-358-de-la-lucha-contra-la-covid-19-venezuela-registra-431-casos-comunitarios-5-importados/ 
We couldn't find the value "2.971.716" on the website and we are not sure what happened. Our hypothesis is that when our script ran the 1st time on 2021-03-11, Venezuela had released the value "2.971.716", and that when it ran a second time later in the day that value was not available anymore . It could be because Venezuela did a mistake or for another reason. The data available now on the tracker is correct.
