### ISSUE TITLE
Malaysia: Cumulative Number Of Performed CV Tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#56]
Hi team,
Could you please take a look on the Malaysia Cumulative Number Of Performed CV Tests,
The values for last 5 observed days have jumped from 2401043 to 7814774 and it looks suspicious for us.
Could you please advise on this if possible?
Thank You

**Comment by ImaneElIdrissi** [comment]
Hello,
Thank you for your comment. I confirm that number 7814774 is correct. Indeed we updated the cumulative number of tests for Malaysia on 03/04/2021. Prior to that the last update was 2401043 on 15/11/2021, hence the drastic increase. Malaysia is one of the countries for which we retrieve testing data manually, due to their way of reporting. They usually do with images on the Ministry of health website or Facebook, images that are not easy to find. In the past days we were able to find some of those images and we were thus able to update our data. We also found one for the 1st of April: https://twitter.com/KKMPutrajaya/status/1377805636306665476.
