### ISSUE TITLE
Thailand Cumulative Number Of Performed CV Tests

### ISSUE THREAD

**Issue by DataOps-epam** [dsbbfinddx/FINDCov19TrackerData#58]
Hi, Could you please check Thailand Cumulative Number Of Performed CV Tests?
We observe suspicious data update as of 06/02/2021
Please advise whether the data are correct
Thank you.

**Comment by ImaneElIdrissi** [comment]
Hello and thank you for your comment.

We retrieve Thailand testing data from the [Ministry of Public Health](http://nextcloud.dmsc.moph.go.th/index.php/s/wbioWZAQfManokc). Unfortunately, MoPH does not release updates on a regular and easy to track manner. For this reason, we were not able to update Thailand testing data since 03/21/2021, explaining why there is a sudden drastic increase. The data is available in the _Thailand_COVID-19_testing_data-update-20210522.xlsx_ file. However, we notice that the value **6161179** was wrongly introduced for the 06/02/2021 while the date mentioned by MoPH is 05/22/2021. This is because we have just automatized this morning the scraping of Thailand testing data. We just made the corresponding modification and which will be soon visible.

Best wishes.
